export const LANGUAGES = {
  en: { label: "English", native: "English" },
  fr: { label: "French", native: "Français" },
  es: { label: "Spanish", native: "Español" },
};

export const t = {
  en: {
    // Home
    tagline: "for the words that stay",
    rotating: [
      "for the one who never knew.",
      "for the version of you that had to let go.",
      "for everything left unsaid.",
      "for the grief that has no name.",
      "for the love that went nowhere.",
    ],
    manifesto_1: "not a diary · not a therapist",
    manifesto_2: "just somewhere to put the words",
    manifesto_3: "that have nowhere else to go",
    begin: "begin",
    have_account: "I have an account",

    // Auth
    forgot_password: "forgot password",
    create_account: "create an account",
    email: "Email",
    password: "Password",
    enter: "enter",
    send_reset: "send reset link",
    reset_password: "reset password",
    new_password: "New Password",
    back_to_login: "back to login",
    check_email: "check your email for a reset link.",
    no_account: "no account?",
    already_account: "already have one?",

    // Onboarding
    onboarding: [
      {
        title: "not a diary.",
        body: "a diary records your days.\nthis is for the words that have no place else to go.",
      },
      {
        title: "not a therapist.",
        body: "no responses. no advice.\njust somewhere quiet to say what you couldn't send.",
      },
      {
        title: "yours alone.",
        body: "no feeds. no public timeline.\nshare only if and when you choose to.",
      },
      {
        title: "whenever you're ready.",
        body: "",
      },
    ],
    skip: "skip",
    continue: "continue",
    begin_writing: "begin writing",

    // Dashboard
    who_is_this_for: "who is this for?",
    welcome_pro: "welcome to unsent pro.",
    streak_2: "you've written two days in a row.",
    streak_3: "three days in a row. keep going.",
    streak_n: (n) => `${n} days. you keep coming back.`,
    streak_default: (n) => `${n} days in a row.`,

    // NewEntry
    write_prompt:
      "write the message you couldn't send.\nthis space is just for you.",
    to_someone: "to someone",
    to_myself: "to myself",
    for_label: "for",
    recipient_placeholder: "a name, a feeling, or leave it open…",
    which_version: "which version?",
    me_then: "me then",
    me_later: "me later",
    age_placeholder: "your age then, or a year…",
    mood_label: "how does this feel",
    moods: [
      "still hurting",
      "finding peace",
      "letting go",
      "missing you",
      "finally free",
      "not yet ready",
      "grateful now",
      "just numb",
    ],
    capsule_label: "seal as time capsule",
    capsule_sub: "lock this until a future date",
    capsule_date_label: "open on",
    capsule_hint: (date) => `this will stay sealed until ${date}`,
    keep_this: "keep this",
    chars: (n) => `${n} chars`,

    // EntryCard
    sealed: "sealed",
    written: "written",
    opens: "opens",
    share: "share",
    reply: "reply",
    cancel: "cancel",
    release: "release",
    let_go: "let this go?",
    yes: "yes",
    no: "no",
    your_reply: "your reply, now",
    reply_placeholder: "what do you want to say back…",
    keep_this_too: "keep this too",
    you_later: "you, later",

    // EntryList
    what_kept: "what you've kept",
    kept_subtitle: "words that never left, but needed somewhere to go",
    how_feeling: "how you've been feeling",
    anniversary_label: "an anniversary",
    anniversary_text: (years) => `${years} today, you wrote something.`,
    on_this_day: "on this day",
    on_this_day_ago: (years) => `${years}, you wrote`,
    close: "close",
    gathering: "gathering your words…",
    nothing_yet: "nothing here yet",
    words_waiting: "the words are waiting.",
    whenever_ready: "whenever you're ready.",
    write_something: "write something",
    one_year_ago: "one year ago",
    years_ago: (n) => `${n} years ago`,

    // Upgrade
    upgrade_title: "unsent pro",
    upgrade_sub: "write without limits.",
    upgrade_perks: [
      "unlimited entries",
      "time capsules",
      "mood timeline",
      "anniversaries",
      "export to pdf",
    ],
    upgrade_price: "$3 / month",
    upgrade_cta: "continue to payment",
    upgrade_limit: "you've reached 20 entries.",
    upgrade_capsule: "time capsules are a pro feature.",
    upgrade_export: "export is a pro feature.",
    upgrade_close: "not now",
  },

  fr: {
    tagline: "pour les mots qui restent",
    rotating: [
      "pour celui ou celle qui n'a jamais su.",
      "pour la version de toi qui a dû lâcher prise.",
      "pour tout ce qui n'a jamais été dit.",
      "pour le deuil sans nom.",
      "pour l'amour qui n'a nulle part où aller.",
    ],
    manifesto_1: "pas un journal · pas un thérapeute",
    manifesto_2: "juste un endroit pour les mots",
    manifesto_3: "qui n'ont nulle part ailleurs où aller",
    begin: "commencer",
    have_account: "j'ai déjà un compte",

    forgot_password: "mot de passe oublié",
    create_account: "créer un compte",
    email: "E-mail",
    password: "Mot de passe",
    enter: "entrer",
    send_reset: "envoyer le lien",
    reset_password: "réinitialiser",
    new_password: "Nouveau mot de passe",
    back_to_login: "retour à la connexion",
    check_email: "vérifiez votre e-mail pour le lien.",
    no_account: "pas de compte ?",
    already_account: "déjà un compte ?",

    onboarding: [
      {
        title: "pas un journal.",
        body: "un journal consigne tes jours.\nceci est pour les mots qui n'ont nulle part où aller.",
      },
      {
        title: "pas un thérapeute.",
        body: "pas de réponses. pas de conseils.\njuste un endroit calme pour dire ce que tu ne pouvais pas envoyer.",
      },
      {
        title: "rien qu'à toi.",
        body: "pas de fil. pas de timeline publique.\npartage seulement si et quand tu le choisis.",
      },
      {
        title: "quand tu seras prêt·e.",
        body: "",
      },
    ],
    skip: "passer",
    continue: "continuer",
    begin_writing: "commencer à écrire",

    who_is_this_for: "pour qui est-ce ?",
    welcome_pro: "bienvenue dans unsent pro.",
    streak_2: "tu as écrit deux jours de suite.",
    streak_3: "trois jours de suite. continue.",
    streak_n: (n) => `${n} jours. tu reviens toujours.`,
    streak_default: (n) => `${n} jours de suite.`,

    write_prompt:
      "écris le message que tu n'as pas pu envoyer.\ncet espace est rien qu'à toi.",
    to_someone: "à quelqu'un",
    to_myself: "à moi-même",
    for_label: "pour",
    recipient_placeholder: "un nom, un sentiment, ou laisse vide…",
    which_version: "quelle version ?",
    me_then: "moi avant",
    me_later: "moi plus tard",
    age_placeholder: "ton âge à l'époque, ou une année…",
    mood_label: "comment tu te sens",
    moods: [
      "toujours blessé·e",
      "trouver la paix",
      "lâcher prise",
      "tu me manques",
      "enfin libre",
      "pas encore prêt·e",
      "reconnaissant·e",
      "juste engourdi·e",
    ],
    capsule_label: "sceller comme capsule temporelle",
    capsule_sub: "verrouiller jusqu'à une date future",
    capsule_date_label: "ouvrir le",
    capsule_hint: (date) => `restera scellé jusqu'au ${date}`,
    keep_this: "garder",
    chars: (n) => `${n} car.`,

    sealed: "scellé",
    written: "écrit",
    opens: "s'ouvre",
    share: "partager",
    reply: "répondre",
    cancel: "annuler",
    release: "relâcher",
    let_go: "laisser partir ?",
    yes: "oui",
    no: "non",
    your_reply: "ta réponse, maintenant",
    reply_placeholder: "qu'est-ce que tu veux dire en retour…",
    keep_this_too: "garder aussi",
    you_later: "toi, plus tard",

    what_kept: "ce que tu as gardé",
    kept_subtitle:
      "des mots qui ne sont jamais partis, mais avaient besoin d'un endroit",
    how_feeling: "comment tu t'es senti·e",
    anniversary_label: "un anniversaire",
    anniversary_text: (years) =>
      `${years} aujourd'hui, tu as écrit quelque chose.`,
    on_this_day: "ce jour-là",
    on_this_day_ago: (years) => `${years}, tu as écrit`,
    close: "fermer",
    gathering: "rassemblons tes mots…",
    nothing_yet: "rien encore",
    words_waiting: "les mots attendent.",
    whenever_ready: "quand tu seras prêt·e.",
    write_something: "écrire quelque chose",
    one_year_ago: "il y a un an",
    years_ago: (n) => `il y a ${n} ans`,

    upgrade_title: "unsent pro",
    upgrade_sub: "écrire sans limites.",
    upgrade_perks: [
      "entrées illimitées",
      "capsules temporelles",
      "chronologie des humeurs",
      "anniversaires",
      "export en pdf",
    ],
    upgrade_price: "3 $ / mois",
    upgrade_cta: "continuer vers le paiement",
    upgrade_limit: "vous avez atteint 20 entrées.",
    upgrade_capsule: "les capsules temporelles sont une fonctionnalité pro.",
    upgrade_export: "l'export est une fonctionnalité pro.",
    upgrade_close: "pas maintenant",
  },

  es: {
    tagline: "para las palabras que se quedan",
    rotating: [
      "para quien nunca lo supo.",
      "para la versión de ti que tuvo que soltar.",
      "para todo lo que quedó sin decir.",
      "para el duelo sin nombre.",
      "para el amor que no fue a ningún lugar.",
    ],
    manifesto_1: "no es un diario · no es un terapeuta",
    manifesto_2: "solo un lugar para las palabras",
    manifesto_3: "que no tienen a dónde ir",
    begin: "comenzar",
    have_account: "ya tengo una cuenta",

    forgot_password: "olvidé mi contraseña",
    create_account: "crear una cuenta",
    email: "Correo",
    password: "Contraseña",
    enter: "entrar",
    send_reset: "enviar enlace",
    reset_password: "restablecer",
    new_password: "Nueva contraseña",
    back_to_login: "volver al inicio",
    check_email: "revisa tu correo para el enlace.",
    no_account: "¿no tienes cuenta?",
    already_account: "¿ya tienes una?",

    onboarding: [
      {
        title: "no es un diario.",
        body: "un diario registra tus días.\nesto es para las palabras que no tienen a dónde ir.",
      },
      {
        title: "no es un terapeuta.",
        body: "sin respuestas. sin consejos.\nsolo un lugar tranquilo para decir lo que no podías enviar.",
      },
      {
        title: "solo tuyo.",
        body: "sin feeds. sin línea de tiempo pública.\ncomparte solo si y cuando lo elijas.",
      },
      {
        title: "cuando estés listo.",
        body: "",
      },
    ],
    skip: "omitir",
    continue: "continuar",
    begin_writing: "comenzar a escribir",

    who_is_this_for: "¿para quién es esto?",
    welcome_pro: "bienvenido a unsent pro.",
    streak_2: "has escrito dos días seguidos.",
    streak_3: "tres días seguidos. sigue así.",
    streak_n: (n) => `${n} días. sigues volviendo.`,
    streak_default: (n) => `${n} días seguidos.`,

    write_prompt:
      "escribe el mensaje que no pudiste enviar.\neste espacio es solo tuyo.",
    to_someone: "a alguien",
    to_myself: "a mí mismo",
    for_label: "para",
    recipient_placeholder: "un nombre, un sentimiento, o déjalo vacío…",
    which_version: "¿qué versión?",
    me_then: "yo antes",
    me_later: "yo después",
    age_placeholder: "tu edad entonces, o un año…",
    mood_label: "cómo se siente esto",
    moods: [
      "aún duele",
      "encontrando paz",
      "soltando",
      "te extraño",
      "por fin libre",
      "aún no listo",
      "agradecido ahora",
      "solo entumecido",
    ],
    capsule_label: "sellar como cápsula del tiempo",
    capsule_sub: "bloquear hasta una fecha futura",
    capsule_date_label: "abrir el",
    capsule_hint: (date) => `permanecerá sellado hasta el ${date}`,
    keep_this: "guardar",
    chars: (n) => `${n} car.`,

    sealed: "sellado",
    written: "escrito",
    opens: "abre",
    share: "compartir",
    reply: "responder",
    cancel: "cancelar",
    release: "soltar",
    let_go: "¿dejar ir esto?",
    yes: "sí",
    no: "no",
    your_reply: "tu respuesta, ahora",
    reply_placeholder: "qué quieres decirle de vuelta…",
    keep_this_too: "guardar esto también",
    you_later: "tú, después",

    what_kept: "lo que has guardado",
    kept_subtitle: "palabras que nunca se fueron, pero necesitaban un lugar",
    how_feeling: "cómo te has sentido",
    anniversary_label: "un aniversario",
    anniversary_text: (years) => `${years} hoy, escribiste algo.`,
    on_this_day: "ese día",
    on_this_day_ago: (years) => `${years}, escribiste`,
    close: "cerrar",
    gathering: "reuniendo tus palabras…",
    nothing_yet: "nada todavía",
    words_waiting: "las palabras esperan.",
    whenever_ready: "cuando estés listo.",
    write_something: "escribir algo",
    one_year_ago: "hace un año",
    years_ago: (n) => `hace ${n} años`,

    upgrade_title: "unsent pro",
    upgrade_sub: "escribe sin límites.",
    upgrade_perks: [
      "entradas ilimitadas",
      "cápsulas del tiempo",
      "línea de tiempo de ánimo",
      "aniversarios",
      "exportar a pdf",
    ],
    upgrade_price: "$3 / mes",
    upgrade_cta: "continuar al pago",
    upgrade_limit: "has alcanzado 20 entradas.",
    upgrade_capsule: "las cápsulas del tiempo son una función pro.",
    upgrade_export: "la exportación es una función pro.",
    upgrade_close: "ahora no",
  },
};
